language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: Jdel4nVT+ckSlCATyioul78AglK88B5/CCx0VUmaOLVQeiOO1PbsxHgiLZhtKJ/0eNWf4JsYKXeN/YvIJMxOq7kcuqSEFaxxZKw+uHgqHEBoYNbTNR4HFig8GLyJFCTLs27GeYVRfXsx9E9KBhz8dAfDGvXnVw87x/qKEtttDM4=
